export const products = [
  {
    id: 1,
    name: "Elegant bag",
    price: 120,
    img: "../../../../public/newarrivalls/newarrivalls1.jpg",
    brand: "Gucci",
    category: "MiniBag",
  },
  {
    id: 2,
    name: "Evening Clutch",
    price: 90,
    img: "../../../../public/newarrivalls/newarrivalls2.jpg",
    brand: "Dior",
    category: "Purse",
  },
  {
    id: 3,
    name: "Work Satchel",
    price: 150,
    img: "../../../../public/newarrivalls/newarrivalls3.jpg",
    brand: "Chanel",
    category: "ToteBag",
  },
  {
    id: 4,
    name: "Work Satchel",
    price: 150,
    img: "../../../../public/newarrivalls/newarrivalls4.jpg",
    brand: "Fendi",
    category: "BigBag",
  },
  {
    id: 5,
    name: "Elegant bag",
    price: 120,
    img: "../../../../public/newarrivalls/newarrivalls1.jpg",
    brand: "Gucci",
    category: "Purse",
  },
  {
    id: 6,
    name: "Evening Clutch",
    price: 90,
    img: "../../../../public/newarrivalls/newarrivalls2.jpg",
    brand: "Chanel",
    category: "MiniBag",
  },
  {
    id: 7,
    name: "Work Satchel",
    price: 150,
    img: "../../../../public/newarrivalls/newarrivalls3.jpg",
    brand: "Dior",
    category: "BigBag",
  },
  {
    id: 8,
    name: "Work Satchel",
    price: 150,
    img: "../../../../public/newarrivalls/newarrivalls4.jpg",
    brand: "Fendi",
    category: "ToteBag",
  },
  {
    id: 9,
    name: "Elegant bag",
    price: 120,
    img: "../../../../public/newarrivalls/newarrivalls1.jpg",
    brand: "Chanel",
    category: "BigBag",
  },
  {
    id: 10,
    name: "Evening Clutch",
    price: 90,
    img: "../../../../public/newarrivalls/newarrivalls2.jpg",
    brand: "Gucci",
    category: "ToteBag",
  },
  {
    id: 11,
    name: "Work Satchel",
    price: 150,
    img: "../../../../public/newarrivalls/newarrivalls3.jpg",
    brand: "Fendi",
    category: "Purse",
  },
  {
    id: 12,
    name: "Work Satchel",
    price: 150,
    img: "../../../../public/newarrivalls/newarrivalls4.jpg",
    brand: "Dior",
    category: "MiniBag",
  },
  {
    id: 13,
    name: "Elegant bag",
    price: 120,
    img: "../../../../public/newarrivalls/newarrivalls1.jpg",
    brand: "Chanel",
    category: "Purse",
  },
  {
    id: 14,
    name: "Evening Clutch",
    price: 90,
    img: "../../../../public/newarrivalls/newarrivalls2.jpg",
    brand: "Fendi",
    category: "BigBag",
  },
  {
    id: 15,
    name: "Work Satchel",
    price: 150,
    img: "../../../../public/newarrivalls/newarrivalls3.jpg",
    brand: "Gucci",
    category: "MiniBag",
  },
  {
    id: 16,
    name: "Work Satchel",
    price: 150,
    img: "../../../../public/newarrivalls/newarrivalls4.jpg",
    brand: "Dior",
    category: "ToteBag",
  },
  {
    id: 17,
    name: "Elegant bag",
    price: 120,
    img: "../../../../public/newarrivalls/newarrivalls1.jpg",
    brand: "Fendi",
    category: "MiniBag",
  },
  {
    id: 18,
    name: "Evening Clutch",
    price: 90,
    img: "../../../../public/newarrivalls/newarrivalls2.jpg",
    brand: "Chanel",
    category: "ToteBag",
  },
  {
    id: 19,
    name: "Work Satchel",
    price: 150,
    img: "../../../../public/newarrivalls/newarrivalls3.jpg",
    brand: "Gucci",
    category: "BigBag",
  },
  {
    id: 20,
    name: "Work Satchel",
    price: 150,
    img: "../../../../public/newarrivalls/newarrivalls4.jpg",
    brand: "Dior",
    category: "Purse",
  },
];
